image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"



test_pep8:
  cache:
    paths:
      - .cache/pip
      - venv/
  script:
    - python -V  # Print out python version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install flake8
    - pip install -r requirements.txt
    - flake8

build_image_master:
  services:
    - docker:dind
  image: docker:latest
  stage: deploy
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin $CI_REGISTRY_1
    - sh ./gitlab.sh
  only:
    - master
  variables:
    DOCKER_HOST: tcp://docker:2375
    CI_REGISTRY_1: https://registry.gitlab.com