version: '3.4'
x-default: &default
  restart: always
  env_file:
    - config.env

services:
  python:
    <<: *default
    build:
      dockerfile: Dockerfile
      context: .
      args:
        database: folder
    volumes:
      - /home/matteo01/Downloads/Telegram Desktop:/data


  db:
    <<: *default
    image: mariadb
    volumes:
      - type: volume
        source: db-Triviabot
        target: /var/lib/mysql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080


volumes:
  db-Triviabot:

